### ISSUE TITLE
Russian language for openslowly

### ISSUE THREAD

**Issue by wvxwxvw** [psimonyi/openslowly#1]
Add a light icon for the dark Firefox theme! Or make an option to disable the icon.

Russian language for openslowly
[ru-RU.zip](https://github.com/psimonyi/openslowly/files/3438706/ru-RU.zip)

**Comment by psimonyi** [comment]
Thanks for translating!
If you're talking about the icon in the context menu, unfortunately Firefox doesn't allow changing or disabling that.  I am updating the icons on the status page for dark mode though.
